
name: google-drive-transfer

# I want to control this manualy
on:
  workflow_dispatch: {}

jobs:
  build:
    name: Build my project 
    runs-on: ubuntu-latest
    steps:
      # space
      
      - name: space before
        run: df -h
      - name: transfer
        run: |
          # get the namne!
          FILENAME=ToneStone-"$(date +"%m-%d-%y-%H:%M")".apk
          echo "test" > $(FILENAME)
          pwd
          ls -lt
          cat $(FILENAME)


      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
          filename: "/github/workspace/$(FILENAME)"
          folderId: ${{ secrets.FOLDER_ID }}
          # name: 'Android/test-file-02-07'  # optional string
          overwrite: "true" # optional boolean
