
name: google-drive-transfer

on:
  schedule:
  # min hou dom mon dow (0=sunday)
  # Time is UTC time!
  # * is a special character in YAML so you have to quote this string
    - cron:  '55 20 * * *'

jobs:
  build:
    name: Build and Transfer to Google Drive 
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: get-date
        run:  echo "::set-output name=today-date::$(date +'%Y-%m-%d-%M')"
      - name: transfer
        run: |
          date > test-file
          md5sum test-file >> test-file
          pwd
          ls -lt
          cat test-file

      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
          filename: "/github/workspace/test-file"
          folderId: ${{ secrets.FOLDER_ID_ANDROID }}
          name: ToneStone-${{ steps.get-date.outputs.today-date }}.apk
          overwrite: "false" # optional boolean
