
name: google-drive-transfer

# I want to control this manualy
on:
  workflow_dispatch: {}

#env:
#   FILENAME: ToneStone-"$(date +"%m-%d-%y-%H:%M")".apk


jobs:
  build:
    name: Build my project 
    runs-on: ubuntu-latest
    steps:
      - name: set_file_name
        run: echo "FILENAME=ToneStone-"$(date +"%m-%d-%y-%H:%M")".apk" >> $GITHUB_ENV
      - name: transfer
        run: |
          echo "test" > ${{ env.FILENAME }}
          pwd
          ls -lt
          cat ${{ env.FILENAME }}

    # ok, lets just use a plain name like we had before

      - name: make plain
        run: echo "blah" > test_file



      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
          filename: test_file
          folderId: ${{ secrets.FOLDER_ID }}
          # name: 'Android/test-file-02-07'  # optional string
          overwrite: "true" # optional boolean
