
name: google-drive-transfer

# I want to control this manualy
on:
  workflow_dispatch: {}

jobs:
  build:
    name: Build my project 
    runs-on: ubuntu-latest
    steps:
      # space
      
      - name: space before
        run: df -h
      - name: transfer
        run: |
          echo "test" > /tmp/test-file
          ls /tmp

      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
          filename: "/tmp/test-file"
          folderId: ${{ secrets.FOLDER_ID }}
          name: "test-file-02-01" # optional string
          overwrite: "true" # optional boolean
