name: space recover

# I want to control this manualy
on:
  workflow_dispatch: {}

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: false
      - name: list docker images
        run: docker image ls -a 
        
        
        #  sh /home/runner/work/kart/kart/.github/workflows/scripts/free_disk_space.sh