
name: space recover

# I want to control this manualy
on:
  workflow_dispatch: {}

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: false
      - name: space before
        run: df -h
      - name: list docker images before
        run: docker image ls -a
      - name: remove images
        run:  docker rmi $(docker image ls -aq)

      - name: list docker images after
        run: docker image ls -a 
      - name: space after
        run: df -h
        
      - name: run-space-script
        run: sh /home/runner/work/kart/kart/.github/workflows/scripts/free_disk_space.sh
      - name: space after running script
        run: df -h
      # lets try removing a couple of other directories
      - name: remove dotnet and boost
        run: | 
            rm -rf /usr/share/dotnet/
            rm -rf "/usr/local/share/boost"
            rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: disk space again
        run: df -h

